version: "2"
linters:
  enable:
    - errorlint
    - gocritic
    - gomodguard
    - importas
    - misspell
    - perfsprint
    - revive
    - testifylint
    - thelper
    - unparam
    - usestdlibvars
    - whitespace
    - wrapcheck
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - assignOp
        - exitAfterDefer
        - typeSwitchVar
    importas:
      alias:
        - pkg: k8s.io/api/apps/v1
          alias: appsv1
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: github.com/argoproj/gitops-engine/pkg/utils/testing
          alias: testingutils
    perfsprint:
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: true
    revive:
      rules:
        - name: bool-literal-in-expr
        - name: blank-imports
          disabled: true
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T,testing.TB'
        - name: context-keys-type
          disabled: true
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
          arguments:
            - preserveScope
        - name: empty-block
          disabled: true
        - name: error-naming
          disabled: true
        - name: error-return
        - name: error-strings
          disabled: true
        - name: errorf
        - name: identical-branches
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
          arguments:
            - preserveScope
        - name: modifies-parameter
        - name: optimize-operands-order
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
          disabled: true
        - name: redundant-import-alias
        - name: superfluous-else
          arguments:
            - preserveScope
        - name: time-equal
        - name: time-naming
          disabled: true
        - name: unexported-return
          disabled: true
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: use-any
        - name: useless-break
        - name: var-declaration
        - name: var-naming
          disabled: true
    testifylint:
      enable-all: true
      disable:
        - go-require
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/diff/internal/fieldmanager/borrowed_.*\.go$
      - internal/kubernetes_vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/argoproj/gitops-engine
  exclusions:
    paths:
      - pkg/diff/internal/fieldmanager/borrowed_.*\.go$
      - internal/kubernetes_vendor
      - third_party$
      - builtin$
      - examples$
