issues:
  exclude-dirs:
    - internal/kubernetes_vendor
  exclude-files:
    - "pkg/diff/internal/fieldmanager/borrowed_.*\\.go$"
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - errcheck
#    - errorlint
    - gocritic
    - gofumpt
#    - goimports
    - gomodguard
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    # Disabled because of https://github.com/argoproj/argo-cd/issues/21705
    # - nolintlint
#    - perfsprint
    - revive
    - staticcheck
    - testifylint
#    - thelper
#    - unparam
    - unused
    - usestdlibvars
    - whitespace
linters-settings:
  gocritic:
    disabled-checks:
      - appendAssign
      - assignOp # Keep it disabled for readability
      - commentFormatting #FIXME
      - exitAfterDefer
      - elseif #FIXME
      - ifElseChain #FIXME
      - mapKey
      - singleCaseSwitch #FIXME
      - typeSwitchVar
      - unlambda #FIXME
      - wrapperFunc #FIXME
  revive:
    # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
    rules:
      - name: bool-literal-in-expr
      - name: blank-imports
        disabled: true
      - name: context-as-argument
        arguments:
          - allowTypesBefore: '*testing.T,testing.TB'
      - name: context-keys-type
        disabled: true
      - name: dot-imports
        disabled: true
      - name: duplicated-imports
        disabled: true
      - name: early-return
        disabled: true
        arguments:
          - 'preserveScope'
      - name: empty-block
        disabled: true
      - name: error-naming
        disabled: true
      - name: error-return
      - name: error-strings
        disabled: true
      - name: errorf
      - name: identical-branches
      - name: if-return
      - name: increment-decrement
        disabled: true
      - name: indent-error-flow
        disabled: true
        arguments:
          - 'preserveScope'
      - name: modifies-parameter
      - name: optimize-operands-order
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
        disabled: true
      - name: redundant-import-alias
        disabled: true
      - name: superfluous-else
        arguments:
          - 'preserveScope'
      - name: time-equal
      - name: time-naming
        disabled: true
      - name: unexported-return
        disabled: true
      - name: unnecessary-stmt
        disabled: true
      - name: unreachable-code
      - name: unused-parameter
      - name: use-any
      - name: useless-break
      - name: var-declaration
      - name: var-naming
        disabled: true
  testifylint:
    enable-all: true
    disable:
      - go-require
      - require-error
run:
  timeout: 5m
