issues:
  exclude-files:
    - "pkg/diff/internal/fieldmanager/borrowed_.*\\.go$"
linters:
  enable:
    - testifylint
linters-settings:
  testifylint:
    enable-all: true
    disable:
      - go-require
      - require-error
